import { chromium } from "playwright";
import { spawn } from "node:child_process";
const S = process.argv[2];
const srv = spawn("node", [new URL("./live.mjs", import.meta.url).pathname], {env:{...process.env, PORT:"3981", DATA_DIR:S+"/dataAnim", ISSUER:"rI", TAXON:"369"}, stdio:"ignore"});
const bye = c => { try { srv.kill(); } catch(e){} process.exit(c); };
setTimeout(() => bye(1), 90000); process.on("uncaughtException", e => { console.log("ERR", e.message); bye(1); });
await new Promise(r => setTimeout(r, 1200));
const br = await chromium.launch({executablePath: process.env.CHROMIUM || undefined});
const p = await br.newPage({viewport:{width:760,height:900}});
p.on("console", m => { if (m.type() === "error") console.log("console:", m.text()); }); p.on("pageerror", e => console.log("pageerror:", e.message));
await p.route(u => !u.href.startsWith("http://127.0.0.1"), r => r.abort());
const shot = async (path) => { const b = await p.evaluate(() => { const r = document.querySelector(".stage").getBoundingClientRect(); return {x:r.x, y:r.y + scrollY, width:r.width, height:r.height}; }); await p.screenshot({path, clip:b, fullPage:true}); };
await p.goto("http://127.0.0.1:3981/"); await p.waitForTimeout(400);
await p.evaluate(() => addEventListener("unhandledrejection", e => console.error("REJ " + (e.reason && e.reason.stack || e.reason))));
await p.evaluate(() => { const c = DATA.fighters.filter(f => f.rarity === 'Common'); startFight(c[0], c[1], false, 5); });
await p.waitForFunction(() => !busy, null, {timeout: 8000});
await p.evaluate(() => { E.hp = E.maxHp = 40; C.bite.miss_chance_saved = C.bite.miss_chance; C.bite.miss_chance = 0; resolve({type:"bite"}, {type:"taunt"}); window.__ev = JSON.stringify(ev); play(); });
console.log("ev:", await p.evaluate(() => window.__ev));
await p.waitForFunction(() => document.querySelector(".chomp"), null, {timeout: 5000, polling: 10});
const tA = Date.now(); console.log("chomp in DOM:", await p.evaluate(() => !!document.querySelector(".chomp"))); await shot(`${S}/sp/bh-1.png`); console.log("shot ms", Date.now() - tA);
await p.waitForTimeout(120); await shot(`${S}/sp/bh-2.png`);
await p.waitForTimeout(200); await shot(`${S}/sp/bh-3.png`);
const i = 3;
console.log("frames", i); await br.close(); bye(0);
