import { spawn } from "node:child_process";
import fs from "node:fs";
import { createHmac } from "node:crypto";
const S = process.argv[2], D = S + "/dataSeason", U = "http://127.0.0.1:3972";
fs.rmSync(D, {recursive:true, force:true}); fs.mkdirSync(D, {recursive:true}); fs.writeFileSync(D + "/session.secret", "testsecret");
const tok = a => { const b0 = Buffer.from(JSON.stringify({a, exp:2e9})).toString("base64url"); return b0 + "." + createHmac("sha256", "testsecret").update(b0).digest("base64url"); };
const acc = n => "rPlayer" + String(n).padStart(21, "0");
const wkOf = d => { const t = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate())); t.setUTCDate(t.getUTCDate() - ((t.getUTCDay() + 6) % 7)); return t.toISOString().slice(0, 10); };
const LAST = wkOf(new Date(Date.now() - 7 * 864e5)), NOW = wkOf(new Date());
const weekly = {}, profiles = {};
const rows = [[1, 900, 20, 5, "moon"], [2, 700, 15, 9, "bone"], [3, 650, 12, 3, "moon"], [4, 400, 9, 14, "moon"], [5, 300, 6, 2, "moon"], [6, 350, 10, 1, "bone"], [7, 0, 0, 0, null]];
for (const [n, xp, wins, losses, pack] of rows) weekly[LAST + "|" + acc(n)] = {account: acc(n), week: LAST, xp, wins, losses, streak: 3, pack};
weekly[NOW + "|" + acc(1)] = {account: acc(1), week: NOW, xp: 30, wins: 1, losses: 0, streak: 1, pack: "moon"};
profiles[acc(1)] = {name: "TopDog"}; profiles[acc(4)] = {name: "Grinder"};
fs.writeFileSync(D + "/store.json", JSON.stringify({players: {}, weekly, holdings: {}, profiles}));
const srv = spawn("node", [new URL("./season-mock.mjs", import.meta.url).pathname], {env:{...process.env, PORT:"3972", DATA_DIR:D, ISSUER:"rI", TAXON:"369", ADMIN_KEY:"adm", XUMM_API_KEY:"k", XUMM_API_SECRET:"s", ORIGIN:"https://game.scrappyxrp.fun"}, stdio:["ignore","ignore","inherit"]});
await new Promise(r => setTimeout(r, 1300));
const get = async (path, who) => (await fetch(U + "/api" + path, {headers: who ? {authorization: "Bearer " + tok(who)} : {}})).json();
const post = async (path, body, who) => (await fetch(U + "/api" + path, {method:"POST", headers:{"content-type":"application/json", ...(who ? {authorization: "Bearer " + tok(who)} : {})}, body: JSON.stringify(body)})).json();
console.log("admin without key:", (await get("/admin/season")).error);
let s = await get("/admin/season?key=adm");
const w = s.weeks.find(x => x.week === LAST);
console.log("treasury:", s.treasury.map(n => "#" + n.token).join(" "), "| last week", LAST, "players", w.players, "sha", w.sha256.slice(0, 16));
console.log("prizes:", w.prizes.map(p => p.place + "=" + p.name + (p.pack ? "(" + p.pack + ")" : "")).join(", "));
console.log("packs:", w.packs.map(p => p.rank + "." + p.id + " " + p.perMember + "/member").join(" | "));
const pub = await (await fetch(U + "/api/public/results")).json();
const { createHash } = await import("node:crypto");
console.log("public: week", pub.week, "| sha matches json:", createHash("sha256").update(pub.json).digest("hex") === pub.sha256, "| anchor", pub.anchor);
const a = await post("/admin/anchor?key=adm", {week: LAST}); console.log("anchor payload:", !!a.uuid);
console.log("anchor status:", JSON.stringify(await get("/admin/xaman?key=adm&uuid=" + a.uuid)));
console.log("anchor again:", (await post("/admin/anchor?key=adm", {week: LAST})).error);
console.log("public anchor:", JSON.stringify((await (await fetch(U + "/api/public/results?week=" + LAST)).json()).anchor));
const pz = await post("/admin/prize?key=adm", {week: LAST, place: "1", nftId: "T102"}); console.log("prize payload:", !!pz.uuid);
await get("/admin/xaman?key=adm&uuid=" + pz.uuid);
console.log("winner prizes:", JSON.stringify((await get("/prizes", acc(1))).prizes));
console.log("other player prizes:", JSON.stringify((await get("/prizes", acc(2))).prizes));
console.log("wrong player claims:", (await post("/prizes/claim", {week: LAST, place: "1"}, acc(2))).error);
const c = await post("/prizes/claim", {week: LAST, place: "1"}, acc(1)); console.log("claim payload:", !!c.uuid, c.offer);
console.log("stranger polls winner's uuid:", (await get("/prizes/status?uuid=" + c.uuid, acc(2))).error);
console.log("claim status:", JSON.stringify(await get("/prizes/status?uuid=" + c.uuid, acc(1))));
console.log("winner prizes after:", JSON.stringify((await get("/prizes", acc(1))).prizes));
s = await get("/admin/season?key=adm");
console.log("treasury after:", s.treasury.map(n => "#" + n.token).join(" "), "| prize row:", JSON.stringify(s.weeks.find(x => x.week === LAST).prizes[0]));
console.log("sha unchanged after prizes:", s.weeks.find(x => x.week === LAST).sha256 === w.sha256);
console.log("this week not closable:", (await post("/admin/anchor?key=adm", {week: NOW})).error);
srv.kill();
